[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "silero-api-server"
version = "0.0.2"
authors = [
  { name="Ouoertheo", email="ouoertheo@tomeofjamin.net" },
]
description = "A simple FastAPI server to host Silero TTS"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ouoertheo/silero-api-server"
"Bug Tracker" = "https://github.com/ouoertheo/silero-api-server/issues"
